### PR TITLE
Keyboard navigation through the left-side tree

### PR DESCRIPTION
**Pull request by AmadeusW**
This PR adds keyboard navigation functionality to the left-side tree
When focus is in the search box,
* `Down arrow` selects next item, either a leaf node or group header
* `Up arrow` selects previous item, either a leaf node or group header
* `Ctrl+down` expands the group, if collapsed group header is selected
* `Ctrl+up` collapses the group, whether user selected leaf node or group header 

Selected item is automatically scrolled into view, if necessary

For example, to get this screenshot, I typed `code` `down` `ctrl up` `down` `down`
2017-07-25_20h30_40

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
Did you consider using Left to select the header when on a child and collapse when on a header? And using Right to expand a collapsed header?

**Comment by AmadeusW** [comment]
left and right are used to move the caret within the search box

**Comment by KirillOsenkov** [comment]
Ah, I see, makes sense.

**Comment by AmadeusW** [comment]
Merged into feature/monaco branch in ddc76f19e49249511bdf22480681fa9932dd94f0

**Pull request closed without merging**
